apiVersion: v1
kind: Pod
metadata:
  name: post-sync-pod
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  restartPolicy: Never
  containers:
  - name: post-sync
    image: busybox
    command: ["sh", "-c", "echo 'PostSync hook pod running...'; sleep 60; echo 'PostSync hook completed.'"]
