apiVersion: v1
kind: Pod
metadata:
  name: pre-sync-pod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  restartPolicy: Never
  containers:
  - name: pre-sync
    image: busybox
    command: ["sh", "-c", "echo 'PreSync hook pod running'; sleep 60; echo 'PreSync hook completed.'"]